# Generated by Django 4.1.6 on 2023-08-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='neme',
            new_name='nome',
        ),
    ]
