# Generated by Django 4.1.6 on 2023-08-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cargo_cargo_alter_servico_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
